// Licensed under GPLv2 or any later version
// Refer to the license.txt file included.
package pkmntv.ui;

/**
 *
 * @author João
 */
public class AboutDialog extends java.awt.Dialog {

    /**
     * Creates new form AboutDialog
     * @param parent
     * @param modal
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLabel = new javax.swing.JLabel();

        setLocationByPlatform(true);
        setResizable(false);
        setTitle("About PkmnTV");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        textLabel.setText("<html>\n<b>Product Name:</b> PkmnTV<br>\n<b>Version:</b> 1.0.2<br>\n<b>Description:</b> A Pokémon type effectivness viewer.<br>\n\t&#8195;&#8195;&#8195;&#8195;&#8195;&#8195;\n\tIt's aim is to provide a faster way to check a Pokémon type <br>\n\t&#8195;&#8195;&#8195;&#8195;&#8195;&#8195;\n\teffectivness without the need of a Internet connection.<br>\n</html>");
        add(textLabel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutDialog dialog = new AboutDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
