/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkmntv.ui;

import java.net.URL;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import pkmntv.dbconn.InfoGetter;
import pkmntv.logic.Pokemon;
import pkmntv.logic.TypeEffect;

/**
 *
 * @author João
 */
public class MainWindow extends javax.swing.JFrame {
    
    private final InfoGetter ig;
    private boolean isFirstQuery = true;
    private boolean showPkmnImage = true;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        ig = new InfoGetter();
        jMenu3.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        idNameLabel = new javax.swing.JLabel();
        type1Button = new javax.swing.JButton();
        type2Button = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        pkmnTextField = new javax.swing.JTextField();
        typeChartPanel = new javax.swing.JPanel();
        normalPanel = new javax.swing.JPanel();
        weakPanel = new javax.swing.JPanel();
        immunePanel = new javax.swing.JPanel();
        resistantPanel = new javax.swing.JPanel();
        pkmnSearchButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        showImgMenuItem = new javax.swing.JCheckBoxMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        idNameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        idNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idNameLabel.setText(" <Name>");

        type1Button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        type1Button.setText("Type1");

        type2Button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        type2Button.setText("Type2");

        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(type1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(type2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(idNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pkmnTextField.setText("Enter Pokemon name");
        pkmnTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pkmnTextFieldFocusGained(evt);
            }
        });
        pkmnTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkmnTextFieldActionPerformed(evt);
            }
        });

        typeChartPanel.setPreferredSize(new java.awt.Dimension(440, 414));
        typeChartPanel.setLayout(new java.awt.GridLayout(4, 1));

        normalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Damaged normally by"));
        normalPanel.setName(""); // NOI18N
        normalPanel.setLayout(new java.awt.GridLayout(2, 10));
        typeChartPanel.add(normalPanel);

        weakPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Weak to"));
        weakPanel.setLayout(new java.awt.GridLayout(2, 10));
        typeChartPanel.add(weakPanel);

        immunePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Immune to"));
        immunePanel.setLayout(new java.awt.GridLayout(2, 2));
        typeChartPanel.add(immunePanel);

        resistantPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Resistant to"));
        resistantPanel.setLayout(new java.awt.GridLayout(2, 10));
        typeChartPanel.add(resistantPanel);

        pkmnSearchButton.setText("Search");
        pkmnSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkmnSearchButtonActionPerformed(evt);
            }
        });

        jMenu3.setText("File");

        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");

        showImgMenuItem.setSelected(true);
        showImgMenuItem.setText("Get Pokemon image");
        jMenu4.add(showImgMenuItem);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pkmnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pkmnSearchButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pkmnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pkmnSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void pkmnTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pkmnTextFieldFocusGained
        pkmnTextField.setText("");
    }//GEN-LAST:event_pkmnTextFieldFocusGained

    private void pkmnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkmnTextFieldActionPerformed
        showPkmnInfo(pkmnTextField.getText().toLowerCase());
    }//GEN-LAST:event_pkmnTextFieldActionPerformed

    private void pkmnSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkmnSearchButtonActionPerformed
        showPkmnInfo(pkmnTextField.getText().toLowerCase());
    }//GEN-LAST:event_pkmnSearchButtonActionPerformed

    private void showPkmnInfo(String name){
        // For the first query is not necessary to clear the type panels.
        if(isFirstQuery)
            isFirstQuery = false;
        else
            clearTypeChart();
        
        Pokemon pkmn = ig.getPkmnInfo(name);
        if(pkmn == null)
            JOptionPane.showMessageDialog(this, 
                    "The Pokemon doesn´t exist.\nPlease try again.", 
                    "Pokemon not found", JOptionPane.ERROR_MESSAGE);
        else{
            String fstType = pkmn.getFirstType();
            String sndType = pkmn.getSecondType();

            if(!ig.getPkmnTypeEffect(fstType, sndType))
                JOptionPane.showMessageDialog(this, 
                        "Could not get the Pokemon type effectivness.\n"
                                + "Please try again.", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            else{
                if(showImgMenuItem.isSelected()){
                    displayPkmnImage(name);
                }
                idNameLabel.setText(pkmn.getName());
                alterTypeButtons(pkmn.getFirstType(), pkmn.getSecondType());
            
                insertTypeChartButtons(normalPanel, TypeEffect.getNormalEffectMap());
                insertTypeChartButtons(weakPanel, TypeEffect.getWeakEffectMap());
                insertTypeChartButtons(immunePanel, TypeEffect.getImmuneEffectMap());
                insertTypeChartButtons(resistantPanel, TypeEffect.getResistantEffectMap());
                
                typeChartPanel.repaint();
                this.pack();
            }
        }  
    }
    
    private void displayPkmnImage(String name){
        URL url = getClass().getClassLoader().getResource("resources/sprites/" + name + ".gif");
        if(url == null)
            JOptionPane.showMessageDialog(this, 
                        "Could not get the Pokemon sprite.\n"
                                + "Please try again.", 
                        "Error", JOptionPane.ERROR_MESSAGE);
        else
            imgLabel.setIcon(new ImageIcon(url));
    }
    
    private void alterTypeButtons(String type1, String type2){
        type1Button.setText(type1);
        type1Button.setBackground(TypeColorMatcher.TC_MAP.get(type1));
        type2Button.setText(type2);
        type2Button.setBackground(TypeColorMatcher.TC_MAP.get(type2));
    }
    
    private void clearTypeChart(){
        normalPanel.removeAll();
        weakPanel.removeAll();
        immunePanel.removeAll();
        resistantPanel.removeAll();
        
        TypeEffect.resetTypeMap();
    }
    
    private void insertTypeChartButtons(JPanel panel, Map map){
        map.forEach((k,v)-> {
            JButton jb = new JButton(k+": "+v+"x");
            jb.setVisible(true);
            jb.setBackground(TypeColorMatcher.TC_MAP.get((String)k));
            panel.add(jb);
                });
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idNameLabel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JPanel immunePanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel normalPanel;
    private javax.swing.JButton pkmnSearchButton;
    private javax.swing.JTextField pkmnTextField;
    private javax.swing.JPanel resistantPanel;
    private javax.swing.JCheckBoxMenuItem showImgMenuItem;
    private javax.swing.JButton type1Button;
    private javax.swing.JButton type2Button;
    private javax.swing.JPanel typeChartPanel;
    private javax.swing.JPanel weakPanel;
    // End of variables declaration//GEN-END:variables
}
